var assert = require('assert');
var path = require('path');

var Scraper = require('../lib/scraper');
var Parser = require('../lib/parser');
var helper = require('../lib/helper');

describe('scraper', function() {
  this.timeout(1000 * 60 * 2);

  it('html', function(done) {
    var parser = new Parser(path.resolve('test/simple-parser.json'));
    var scraper = new Scraper();

    var opts = {
      usePhantom: false,
      parser: parser,
      dumpFile: helper.tmpName({prefix: 'non-js', postfix: '.html', dir: helper.getAppTmpDir()})
    };

    scraper.scrapePage('http://www.jufengshang.com/Longines3756', opts, function(err, result) {
      console.log(result);

      assert(result);
      assert(result.title);
      assert(result.imgSrc);
      assert(result.description);

      done(err);
    });
  });

  it.only('html with js', function(done) {
    var parser = new Parser(path.resolve('test/simple-parser.json'));
    parser.mapping.price = '.shop_s';  // this element is generated by js

    var opts = {
      usePhantom: true,
      parser: parser,
      dumpFile: helper.tmpName({prefix: 'js', postfix: '.html', dir: helper.getAppTmpDir()})
    };

    var scraper = new Scraper();

    var uri = 'http://www.jufengshang.com/Longines3756';
    scraper.scrapePage(uri, opts, function(err, result) {
      console.log(result);

      assert(result);
      assert(result.title);
      assert(result.imgSrc);
      assert(result.description);
      assert(result.price);

      done(err);
    });
  });
});