var assert = require('assert');
var path = require('path');

var fse = require('fs-extra');

var helper = require('../lib/helper');
var Scraper = require('../lib/scraper');
var SimpleProcessor = require('../lib/processor').SimpleProcessor;
var imageDownloadProcessor = require('../lib/processor').ImageDownloadProcessor;
var fileDumpProcessor = require('../lib/processor').FileDumpProcessor;

describe('scraper', function() {
  this.timeout(1000 * 60 * 2);

  it('html', function(done) {
    var simpleProcessor = new SimpleProcessor(path.resolve('test/simple-parser.json'));
    var scraper = new Scraper([simpleProcessor, imageDownloadProcessor, fileDumpProcessor]);

    var downloadDir = simpleProcessor.mapping.imgSrc.downloadDir;
    fse.ensureDirSync(downloadDir);

    var opts = {
      uri: 'http://www.jufengshang.com/Longines3756',
      dumpFile: helper.tmpName({prefix: 'non-js', postfix: '.html', dir: helper.getAppTmpDir()})
    };

    scraper.scrapePage(opts, function(err, result) {
      console.log(result);

      assert(result);
      assert(result.title);
      assert(result.imgSrc);
      assert(result.description);

      var downloadedImage = path.join(downloadDir, path.basename(result.imgSrc));

      assert(result.downloadImgSrc == downloadedImage);
      assert(fse.existsSync(downloadedImage));
      assert(fse.existsSync(opts.dumpFile));

      fse.removeSync(downloadDir);

      done(err);
    });
  });

  it('html with js', function(done) {
    var simpleProcessor = new SimpleProcessor(path.resolve('test/simple-parser.json'));
    simpleProcessor.mapping.price = '.shop_s';  // this element is generated by js

    var scraper = new Scraper([simpleProcessor, imageDownloadProcessor, fileDumpProcessor]);

    var opts = {
      uri: 'http://www.jufengshang.com/Longines3756',
      usePhantom: true,
      dumpFile: helper.tmpName({prefix: 'js', postfix: '.html', dir: helper.getAppTmpDir()})
    };

    scraper.scrapePage(opts, function(err, result) {
      console.log(result);

      assert(result);
      assert(result.title);
      assert(result.imgSrc);
      assert(result.description);
      assert(result.price);

      done(err);
    });
  });
});